plugins:
  - jekyll-remote-theme
remote_theme: vfvong/jekyll-theme-tao

# Site config
title: Taboola Rasa
tagline: A Clean Slate For Mental Health
description: Taboola Rasa is a non-profit mental health advocacy project

author:
  name:   Taboola Rasa
  url:    https://taboolarasa.org
  avatar: ./assets/img/taboola-rasa-avatar.jpg

# plugins:
#   - jekyll-paginate

# paginate: 2

# categories_path: /categories/
# tags_path: /tags/